// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Modules.Tenancy.Infrastructure;

#nullable disable

namespace Platform.Modules.Tenancy.Infrastructure.Migrations
{
    [DbContext(typeof(TenancyDbContext))]
    partial class TenancyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenancy")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Infrastructure.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_entries_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_tenant_id_occurred_at");

                    b.ToTable("audit_entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_email");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_name");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("TargetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_label");

                    b.Property<string>("TargetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_tenant_id_created_at");

                    b.HasIndex("TenantId", "ActorId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_tenant_id_actor_id_created_at");

                    b.HasIndex("TenantId", "Severity", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_tenant_id_severity_created_at");

                    b.ToTable("audit_events", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "tenancy");
                });

            modelBuilder.Entity("Platform.Infrastructure.Persistence.NumberSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint")
                        .HasColumnName("next_value");

                    b.HasKey("TenantId", "Name")
                        .HasName("pk_number_sequences");

                    b.ToTable("number_sequences", "tenancy");
                });

            modelBuilder.Entity("Platform.Modules.Tenancy.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("default_currency")
                        .IsFixedLength();

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("default_locale");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PlanCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan_code");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("website_url");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Platform.Modules.Tenancy.Domain.Tenant.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_country");

                            b1.Property<string>("Line1")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_state");
                        });

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", "tenancy");
                });

            modelBuilder.Entity("Platform.Modules.Tenancy.Domain.TenantDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("citext")
                        .HasColumnName("host");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("verification_token");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant_domains");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_domains_host");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_domains_tenant_id");

                    b.ToTable("tenant_domains", "tenancy");
                });

            modelBuilder.Entity("Platform.Modules.Tenancy.Domain.TenantSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_settings_tenant_id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_settings_tenant_id_key");

                    b.ToTable("settings", "tenancy");
                });

            modelBuilder.Entity("Platform.Modules.Tenancy.Domain.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("About")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("about");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("Established")
                        .HasColumnType("date")
                        .HasColumnName("established");

                    b.Property<bool>("HoldsMembers")
                        .HasColumnType("boolean")
                        .HasColumnName("holds_members");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Locality")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("locality");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("path");

                    b.PrimitiveCollection<List<string>>("Phones")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("phones");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Tagline")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("tagline");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_units_parent_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_units_tenant_id");

                    b.HasIndex("TenantId", "Kind")
                        .HasDatabaseName("ix_units_tenant_id_kind");

                    b.HasIndex("TenantId", "Path")
                        .HasDatabaseName("ix_units_tenant_id_path");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("TenantId", "Path"), new[] { "uuid_ops", "text_pattern_ops" });

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_units_tenant_id_slug")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("TenantId", "ParentId", "SortOrder")
                        .HasDatabaseName("ix_units_tenant_id_parent_id_sort_order");

                    b.ToTable("units", "tenancy");
                });

            modelBuilder.Entity("Platform.Modules.Tenancy.Domain.TenantDomain", b =>
                {
                    b.HasOne("Platform.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany("Domains")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_domains_tenants_tenant_id");
                });

            modelBuilder.Entity("Platform.Modules.Tenancy.Domain.Unit", b =>
                {
                    b.HasOne("Platform.Modules.Tenancy.Domain.Unit", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_units_units_parent_id");

                    b.OwnsOne("Platform.SharedKernel.Domain.ImageRef", "Avatar", b1 =>
                        {
                            b1.Property<Guid>("UnitId");

                            b1.Property<string>("Alt")
                                .IsRequired();

                            b1.Property<int?>("Height");

                            b1.Property<string>("Placeholder");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.Property<int?>("Width");

                            b1.HasKey("UnitId");

                            b1.ToTable("units", "tenancy");

                            b1
                                .ToJson("avatar")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UnitId")
                                .HasConstraintName("fk_units_units_id");
                        });

                    b.OwnsOne("Platform.SharedKernel.Domain.ImageRef", "Cover", b1 =>
                        {
                            b1.Property<Guid>("UnitId");

                            b1.Property<string>("Alt")
                                .IsRequired();

                            b1.Property<int?>("Height");

                            b1.Property<string>("Placeholder");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.Property<int?>("Width");

                            b1.HasKey("UnitId")
                                .HasName("pk_units");

                            b1.ToTable("units", "tenancy");

                            b1
                                .ToJson("cover")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UnitId")
                                .HasConstraintName("fk_units_units_unit_id");
                        });

                    b.OwnsMany("Platform.Modules.Tenancy.Domain.UnitLeader", "Leaders", b1 =>
                        {
                            b1.Property<Guid>("UnitId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("PersonSlug");

                            b1.Property<string>("Role")
                                .IsRequired();

                            b1.HasKey("UnitId", "__synthesizedOrdinal");

                            b1.ToTable("units", "tenancy");

                            b1
                                .ToJson("leaders")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UnitId")
                                .HasConstraintName("fk_units_units_unit_id");
                        });

                    b.Navigation("Avatar");

                    b.Navigation("Cover");

                    b.Navigation("Leaders");
                });

            modelBuilder.Entity("Platform.Modules.Tenancy.Domain.Tenant", b =>
                {
                    b.Navigation("Domains");
                });
#pragma warning restore 612, 618
        }
    }
}
