apiVersion: v1
kind: Service
metadata:
  name: platform-api-service
  namespace: platform
  labels:
    app.kubernetes.io/name: platform-api
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: platform-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

