apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.template.yaml
  - pvc.yaml
  - migration-job.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - api-service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/part-of: esocs-digital-platform

